sonar.projectKey=AntonAzer_cvbackend
sonar.organization=AntonAzer
sonar.sources=.
sonar.exclusions=node_modules/**, coverage/**, dist/**, build/**

# لو المشروع TypeScript أو JavaScript وفيه Coverage reports (اختياري)
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
